apiVersion: apps/v1
kind: Deployment
metadata:
  name: restmcrd-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: restmcrd-api
  template:
    metadata:
      labels:
        app: restmcrd-api
    spec:
      containers:
      - name: restmcrd-api
        image: gcr.io/restmcrd/restmcrd:latest
        ports:
        - containerPort: 80